using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Kentzi
{
	public class KentziReceipt : KentziBase
    {
		public KentziReceipt() {}

        public KentziReceipt(string mobileNumber, string storeId, string receiptCode, double amount, double discount, string hostName, DateTime dateTime, List<KentziLineItem> lineItems)
        {
			
            this.mobileNumber = mobileNumber;
            this.store = storeId;
            this.code = receiptCode;
            this.amount = amount;
            this.discount = discount;
            this.host_name = hostName;
            this.date = dateTime;
            this.lineItems = lineItems;
        }
        
		/// <summary>
		/// The mobile number where the SMS will be sent with the summary of the receipt
		/// </summary>
        public String mobileNumber { get; set; }
		/// <summary>
		/// The Id assignede to each store
		/// </summary>
        public string store { get; set; }
		/// <summary>
		/// The unique receipt code generated by the store
		/// </summary>
        public string code { get; set; }
		/// <summary>
		/// The amount in the receipt
		/// </summary>
        public double amount { get; set; }
		/// <summary>
		/// Discount applied on the receipt, if applies
		/// </summary>
        public double discount { get; set; }
		/// <summary>
		/// The name of the machine where this receipt was generated
		/// </summary>
        public string host_name { get; set; }
		/// <summary>
		/// Date and time when the receipt was generated
		/// </summary>
        public DateTime date { get; set; }
		/// <summary>
		/// A list with the products in the receipt
		/// </summary>
        public List<KentziLineItem> lineItems { get; set; }
    }
}
